In [21]:
import pandas as pd

In [22]:
custome = pd.read_csv('../dataset/customerdata.csv')
custome.head(2)

,Unnamed: 0,CUSTID,AVGPRICE,EMI,DEVICECOUNT,PRODUCTAGE,CUSTTYPE2
0,0,A13566,4273.90000,3,6.4,1.679181,Big-Screen-lover
1,1,A14219,3642.44195,2,4.0,2.682023,Sleeping-dog

In [23]:
custome[(custome.EMI >= 3) &
       (custome.DEVICECOUNT >= 5)]

,Unnamed: 0,CUSTID,AVGPRICE,EMI,DEVICECOUNT,PRODUCTAGE,CUSTTYPE2
0,0,A13566,4273.900000,3,6.4,1.679181,Big-Screen-lover
27,27,F17131,3179.708359,3,6.5,1.100000,Early-bird
33,33,G16437,3787.328898,3,6.7,1.000000,Early-bird
36,36,G18402,3402.199381,3,6.5,1.000000,Early-bird
40,40,H16326,3988.935304,3,6.5,0.900000,Early-bird
45,45,I12899,3018.895637,3,6.4,0.900000,Early-bird
51,51,J10809,3676.135627,3,6.5,0.800000,Early-bird
52,52,J15083,2811.265932,3,6.0,0.900000,Early-bird
53,53,J16445,3041.848186,3,6.4,0.800000,Early-bird
60,60,L13892,3263.515145,3,6.7,1.100000,Early-bird
67,67,N13273,3839.694732,3,6.9,1.100000,Early-bird
95,95,R16364,3592.353540,3,6.2,0.900000,Early-bird
107,107,S17396,3895.200000,3,6.1,2.055707,Big-Screen-lover
113,113,T11473,4165.700000,3,6.7,1.780674,Big-Screen-lover
126,126,V18566,3527.701867,3,6.5,0.900000,Early-bird
130,130,W13404,4296.873743,3,6.5,1.100000,Early-bird
135,135,X13390,2947.543982,3,6.3,1.100000,Early-bird
142,142,Z11525,3259.018704,3,6.4,0.900000,Early-bird
146,146,Z13534,3662.437527,3,6.6,0.900000,Early-bird

In [24]:
custome.dtypes

Unnamed: 0       int64
CUSTID          object
AVGPRICE       float64
EMI              int64
DEVICECOUNT    float64
PRODUCTAGE     float64
CUSTTYPE2       object
dtype: object

### 원하는 컬럼만 조회하기

In [25]:
csData = pd.read_csv("../dataset/kopo_customerdata.csv")
csData.head(5)

,CUSTOMERCODE,STATENAME,ST,GENDER,DOB,GENDER1,EMAIL,FEST_CNT,TOTAL_AMOUNT,AC_AMOUNT,AV_AMOUNT,HA_AMOUNT,EMI_CE_AMOUNT,IS_HIGHEND,CNT_VIST,GAP_VISIT
0,1503989,State2,2,Male,0,1,1,0,30300,0,30300,0,0,0,1,0
1,1190338,State2,2,Male,0,1,0,1,46500,0,46500,0,0,0,1,0
2,1424715,State2,2,Female,0,2,0,0,22700,0,0,22700,0,0,1,0
3,2483305,State2,2,Male,0,1,0,1,31400,0,31400,0,0,0,1,0
4,1178802,State2,2,Male,0,1,0,1,44900,0,0,44900,0,0,1,0

In [26]:
csDataC = csData[["CUSTOMERCODE","STATENAME","GENDER","TOTAL_AMOUNT"]]
##변수에 넣어준 후 사용하기
csDataC.head(5)

   CUSTOMERCODE STATENAME  GENDER  TOTAL_AMOUNT
0       1503989    State2    Male         30300
1       1190338    State2    Male         46500
2       1424715    State2  Female         22700
3       2483305    State2    Male         31400
4       1178802    State2    Male         44900

### index로 데이터 조회하기

In [27]:
dfc1 = csData.iloc[0:4,1:4]
##iloc앞 :이 행 뒤가 열 = 0,1,2,3행을 불러오고 0,1,2,3,4열을 가져와라
dfc1

  STATENAME  ST  GENDER
0    State2   2    Male
1    State2   2    Male
2    State2   2  Female
3    State2   2    Male

### list로 읽고 가져오기

In [28]:
csDataColumns = csData.columns

In [29]:
csCodeColNo = csDataColumns.get_loc("CUSTOMERCODE")
stColNo = csDataColumns.get_loc("ST")
## get_loc은 = get_location = 위치를 뽑아라

In [30]:
csData.iloc[:,[csCodeColNo,stColNo]].head(5)

   CUSTOMERCODE  ST
0       1503989   2
1       1190338   2
2       1424715   2
3       2483305   2
4       1178802   2

### list로 읽고 가져오기2

In [31]:
csData.iloc[0:5,[0,2]]

   CUSTOMERCODE  ST
0       1503989   2
1       1190338   2
2       1424715   2
3       2483305   2
4       1178802   2

### 4.데이터 조작하기

In [32]:
csDATA2 = pd.read_csv("../dataset/customerdata.csv")

In [33]:
import numpy as np

In [34]:
csDATA2["PRODUCTAGE_age_NEW"] = np.where(csDATA2["PRODUCTAGE"]<1,1,\
                            np.where(csDATA2["PRODUCTAGE"]<2,2,\
                            np.where(csDATA2["PRODUCTAGE"]<3,3,\
                                    5)))
csDATA2.head(5)

,Unnamed: 0,CUSTID,AVGPRICE,EMI,DEVICECOUNT,PRODUCTAGE,CUSTTYPE2,PRODUCTAGE_age_NEW
0,0,A13566,4273.900000,3,6.4,1.679181,Big-Screen-lover,2
1,1,A14219,3642.441950,2,4.0,2.682023,Sleeping-dog,3
2,2,A15312,3653.884565,2,5.0,3.208202,Sleeping-dog,5
3,3,A16605,3713.211107,2,6.6,0.900000,Early-bird,1
4,4,B10634,3391.074215,2,4.2,2.453656,Sleeping-dog,3

### 4.이상데이터 정제하기

In [35]:
# 컬럼 추가 생성 및 조건에 따른 컬럼명 변경
def refining(df):
    if df['PRODUCTAGE'] < 1:
        return 1
    elif df['PRODUCTAGE'] <2:
        return 2
    else:
        return 5
csDATA2["PRODUCTAGE_NEW2"] = csDATA2.apply(refining,axis=1)
csDATA2

,Unnamed: 0,CUSTID,AVGPRICE,EMI,DEVICECOUNT,PRODUCTAGE,CUSTTYPE2,PRODUCTAGE_age_NEW,PRODUCTAGE_NEW2
0,0,A13566,4273.900000,3,6.4,1.679181,Big-Screen-lover,2,2
1,1,A14219,3642.441950,2,4.0,2.682023,Sleeping-dog,3,5
2,2,A15312,3653.884565,2,5.0,3.208202,Sleeping-dog,5,5
3,3,A16605,3713.211107,2,6.6,0.900000,Early-bird,1,1
4,4,B10634,3391.074215,2,4.2,2.453656,Sleeping-dog,3,5
5,5,B16849,3755.263391,2,4.7,2.786665,Sleeping-dog,3,5
6,6,B18816,3213.911446,2,6.4,0.900000,Early-bird,1,1
7,7,C10639,3516.500000,2,5.2,2.564830,Big-Screen-lover,3,5
8,8,C12717,3732.900000,2,5.7,2.069995,Big-Screen-lover,3,5
9,9,C15050,4020.173425,2,4.9,3.013440,Sleeping-dog,5,5
10,10,C18306,4005.005142,2,4.7,3.113618,Sleeping-dog,5,5
11,11,C18622,3246.000000,1,5.0,1.891624,Big-Screen-lover,2,2
12,12,C19178,3624.700000,2,5.6,2.137246,Big-Screen-lover,3,5
13,13,D11795,2991.014703,2,6.4,0.800000,Early-bird,1,1
14,14,D13030,3227.855655,2,4.8,3.467370,Sleeping-dog,5,5
15,15,D15289,4165.700000,2,6.9,2.911016,Big-Screen-lover,3,5
16,16,D17241,4166.533130,2,4.7,2.577757,Sleeping-dog,3,5
17,17,D17880,3383.145853,2,4.5,2.903990,Sleeping-dog,3,5
18,18,E10778,4165.700000,2,6.7,2.122257,Big-Screen-lover,3,5
19,19,E11917,3516.500000,2,5.5,2.087540,Big-Screen-lover,3,5
20,20,E16075,3418.048887,2,4.2,2.771469,Sleeping-dog,3,5
21,21,E16221,3408.300000,2,5.0,1.988682,Big-Screen-lover,2,2
22,22,E18145,3408.300000,2,4.9,1.521029,Big-Screen-lover,2,2
23,23,E19404,3764.940414,2,6.5,0.900000,Early-bird,1,1
24,24,F10222,3191.065822,2,6.5,0.900000,Early-bird,1,1
25,25,F12979,4165.700000,2,6.1,2.128362,Big-Screen-lover,3,5
26,26,F14866,3137.800000,2,5.1,1.725892,Big-Screen-lover,2,2
27,27,F17131,3179.708359,3,6.5,1.100000,Early-bird,2,2
28,28,F18646,3334.244233,2,4.5,3.273196,Sleeping-dog,5,5
29,29,F19938,3732.900000,2,5.4,2.011303,Big-Screen-lover,3,5
...,...,...,...,...,...,...,...,...,...
120,120,U16894,3234.465609,2,3.6,2.606419,Sleeping-dog,3,5
121,121,U17547,3313.905655,2,4.0,2.448368,Sleeping-dog,3,5
122,122,U17748,3394.152840,2,4.0,2.185742,Sleeping-dog,3,5
123,123,V10654,3902.329790,2,4.6,3.260149,Sleeping-dog,5,5
124,124,V16516,3149.259875,2,4.1,2.410823,Sleeping-dog,3,5
125,125,V16704,2605.631083,2,6.6,0.900000,Early-bird,1,1
126,126,V18566,3527.701867,3,6.5,0.900000,Early-bird,1,1
127,127,V19072,3462.400000,2,5.3,1.922932,Big-Screen-lover,2,2
128,128,W10832,3527.360507,2,4.1,2.136971,Sleeping-dog,3,5
129,129,W13032,4003.400000,2,6.1,2.519623,Big-Screen-lover,3,5
130,130,W13404,4296.873743,3,6.5,1.100000,Early-bird,2,2
131,131,W13995,2411.008838,2,6.4,1.000000,Early-bird,2,2
132,132,W16193,3402.729703,2,6.4,0.900000,Early-bird,1,1
133,133,W18228,3480.455474,2,6.4,0.900000,Early-bird,1,1
134,134,X10158,3949.300000,2,6.3,1.815666,Big-Screen-lover,2,2
135,135,X13390,2947.543982,3,6.3,1.100000,Early-bird,2,2
136,136,X14259,3481.314549,2,4.3,2.528063,Sleeping-dog,3,5
137,137,X19598,3516.500000,2,5.1,2.646259,Big-Screen-lover,3,5
138,138,X19768,3486.085831,2,4.6,2.835355,Sleeping-dog,3,5
139,139,Y10906,3408.300000,2,6.0,2.131432,Big-Screen-lover,3,5
140,140,Y12458,2976.211190,1,3.5,2.199677,Sleeping-dog,3,5
141,141,Y13678,3408.300000,2,5.6,2.084005,Big-Screen-lover,3,5
142,142,Z11525,3259.018704,3,6.4,0.900000,Early-bird,1,1
143,143,Z12343,3498.896985,2,6.6,0.900000,Early-bird,1,1
144,144,Z12772,3029.600000,2,4.9,2.093035,Big-Screen-lover,3,5
145,145,Z13253,3678.800000,2,5.9,2.463670,Big-Screen-lover,3,5
146,146,Z13534,3662.437527,3,6.6,0.900000,Early-bird,1,1
147,147,Z16428,3516.500000,2,5.8,2.371301,Big-Screen-lover,3,5
148,148,Z16735,3300.100000,2,5.6,1.704942,Big-Screen-lover,2,2
149,149,Z19835,3326.526183,2,6.7,1.200000,Early-bird,2,2

### 5. 데이터 정렬하기

In [36]:
sortKey = ["CUSTID","AVGPRICE"]

In [37]:
# csDATA2.sort_values(["CUSTID","AVGPRICE"], ascending=[True,False])
sortedData = csDATA2.sort_values(sortKey)
sortedData.head(5)

#변수를 사용하면 메모리를 많이 먹는다. 또한 정렬한 것을 변수로 넣어야만 정렬된 채로 나옴 안그럼 복귀됨

,Unnamed: 0,CUSTID,AVGPRICE,EMI,DEVICECOUNT,PRODUCTAGE,CUSTTYPE2,PRODUCTAGE_age_NEW,PRODUCTAGE_NEW2
0,0,A13566,4273.900000,3,6.4,1.679181,Big-Screen-lover,2,2
1,1,A14219,3642.441950,2,4.0,2.682023,Sleeping-dog,3,5
2,2,A15312,3653.884565,2,5.0,3.208202,Sleeping-dog,5,5
3,3,A16605,3713.211107,2,6.6,0.900000,Early-bird,1,1
4,4,B10634,3391.074215,2,4.2,2.453656,Sleeping-dog,3,5

###  6.그룹으로 묶어서 데이터 요약분석하기

In [18]:
groupKey = ["EMI"]

### 7. rolling함수

In [41]:
csDATA2["TEST"] = csDATA2["PRODUCTAGE"].rolling(window = 5, center = False).mean()
csDATA2
#예전에 엑셀할때 변동률 및 계절성지수에서 위아래 5개했던거 기억
#rolling을 사용할 때, groupby개념을 잡고 있어야 한다.

,Unnamed: 0,CUSTID,AVGPRICE,EMI,DEVICECOUNT,PRODUCTAGE,CUSTTYPE2,PRODUCTAGE_age_NEW,PRODUCTAGE_NEW2,TEST
0,0,A13566,4273.900000,3,6.4,1.679181,Big-Screen-lover,2,2,NaN
1,1,A14219,3642.441950,2,4.0,2.682023,Sleeping-dog,3,5,NaN
2,2,A15312,3653.884565,2,5.0,3.208202,Sleeping-dog,5,5,NaN
3,3,A16605,3713.211107,2,6.6,0.900000,Early-bird,1,1,NaN
4,4,B10634,3391.074215,2,4.2,2.453656,Sleeping-dog,3,5,2.184612
5,5,B16849,3755.263391,2,4.7,2.786665,Sleeping-dog,3,5,2.406109
6,6,B18816,3213.911446,2,6.4,0.900000,Early-bird,1,1,2.049705
7,7,C10639,3516.500000,2,5.2,2.564830,Big-Screen-lover,3,5,1.921030
8,8,C12717,3732.900000,2,5.7,2.069995,Big-Screen-lover,3,5,2.155029
9,9,C15050,4020.173425,2,4.9,3.013440,Sleeping-dog,5,5,2.266986
10,10,C18306,4005.005142,2,4.7,3.113618,Sleeping-dog,5,5,2.332377
11,11,C18622,3246.000000,1,5.0,1.891624,Big-Screen-lover,2,2,2.530702
12,12,C19178,3624.700000,2,5.6,2.137246,Big-Screen-lover,3,5,2.445185
13,13,D11795,2991.014703,2,6.4,0.800000,Early-bird,1,1,2.191186
14,14,D13030,3227.855655,2,4.8,3.467370,Sleeping-dog,5,5,2.281972
15,15,D15289,4165.700000,2,6.9,2.911016,Big-Screen-lover,3,5,2.241451
16,16,D17241,4166.533130,2,4.7,2.577757,Sleeping-dog,3,5,2.378678
17,17,D17880,3383.145853,2,4.5,2.903990,Sleeping-dog,3,5,2.532027
18,18,E10778,4165.700000,2,6.7,2.122257,Big-Screen-lover,3,5,2.796478
19,19,E11917,3516.500000,2,5.5,2.087540,Big-Screen-lover,3,5,2.520512
20,20,E16075,3418.048887,2,4.2,2.771469,Sleeping-dog,3,5,2.492603
21,21,E16221,3408.300000,2,5.0,1.988682,Big-Screen-lover,2,2,2.374788
22,22,E18145,3408.300000,2,4.9,1.521029,Big-Screen-lover,2,2,2.098196
23,23,E19404,3764.940414,2,6.5,0.900000,Early-bird,1,1,1.853744
24,24,F10222,3191.065822,2,6.5,0.900000,Early-bird,1,1,1.616236
25,25,F12979,4165.700000,2,6.1,2.128362,Big-Screen-lover,3,5,1.487615
26,26,F14866,3137.800000,2,5.1,1.725892,Big-Screen-lover,2,2,1.435057
27,27,F17131,3179.708359,3,6.5,1.100000,Early-bird,2,2,1.350851
28,28,F18646,3334.244233,2,4.5,3.273196,Sleeping-dog,5,5,1.825490
29,29,F19938,3732.900000,2,5.4,2.011303,Big-Screen-lover,3,5,2.047751
...,...,...,...,...,...,...,...,...,...,...
120,120,U16894,3234.465609,2,3.6,2.606419,Sleeping-dog,3,5,2.383817
121,121,U17547,3313.905655,2,4.0,2.448368,Sleeping-dog,3,5,2.311081
122,122,U17748,3394.152840,2,4.0,2.185742,Sleeping-dog,3,5,2.568229
123,123,V10654,3902.329790,2,4.6,3.260149,Sleeping-dog,5,5,2.561750
124,124,V16516,3149.259875,2,4.1,2.410823,Sleeping-dog,3,5,2.582300
125,125,V16704,2605.631083,2,6.6,0.900000,Early-bird,1,1,2.241016
126,126,V18566,3527.701867,3,6.5,0.900000,Early-bird,1,1,1.931343
127,127,V19072,3462.400000,2,5.3,1.922932,Big-Screen-lover,2,2,1.878781
128,128,W10832,3527.360507,2,4.1,2.136971,Sleeping-dog,3,5,1.654145
129,129,W13032,4003.400000,2,6.1,2.519623,Big-Screen-lover,3,5,1.675905
130,130,W13404,4296.873743,3,6.5,1.100000,Early-bird,2,2,1.715905
131,131,W13995,2411.008838,2,6.4,1.000000,Early-bird,2,2,1.735905
132,132,W16193,3402.729703,2,6.4,0.900000,Early-bird,1,1,1.531319
133,133,W18228,3480.455474,2,6.4,0.900000,Early-bird,1,1,1.283925
134,134,X10158,3949.300000,2,6.3,1.815666,Big-Screen-lover,2,2,1.143133
135,135,X13390,2947.543982,3,6.3,1.100000,Early-bird,2,2,1.143133
136,136,X14259,3481.314549,2,4.3,2.528063,Sleeping-dog,3,5,1.448746
137,137,X19598,3516.500000,2,5.1,2.646259,Big-Screen-lover,3,5,1.797998
138,138,X19768,3486.085831,2,4.6,2.835355,Sleeping-dog,3,5,2.185069
139,139,Y10906,3408.300000,2,6.0,2.131432,Big-Screen-lover,3,5,2.248222
140,140,Y12458,2976.211190,1,3.5,2.199677,Sleeping-dog,3,5,2.468157
141,141,Y13678,3408.300000,2,5.6,2.084005,Big-Screen-lover,3,5,2.379346
142,142,Z11525,3259.018704,3,6.4,0.900000,Early-bird,1,1,2.030094
143,143,Z12343,3498.896985,2,6.6,0.900000,Early-bird,1,1,1.643023
144,144,Z12772,3029.600000,2,4.9,2.093035,Big-Screen-lover,3,5,1.635343
145,145,Z13253,3678.800000,2,5.9,2.463670,Big-Screen-lover,3,5,1.688142
146,146,Z13534,3662.437527,3,6.6,0.900000,Early-bird,1,1,1.451341
147,147,Z16428,3516.500000,2,5.8,2.371301,Big-Screen-lover,3,5,1.745601
148,148,Z16735,3300.100000,2,5.6,1.704942,Big-Screen-lover,2,2,1.906590
149,149,Z19835,3326.526183,2,6.7,1.200000,Early-bird,2,2,1.727983

### 8.데이터 합치기

In [44]:
import pandas as pd
regionMasterData = pd.read_csv('../dataset/kopo_region_mst.csv')
selectExample = pd.read_csv('../dataset/kopo_channel_seasonality_new.csv')

In [45]:
regionMasterData.head()

  REGIONID REGIONNAME
0      A00     AFRICA
1      A01    AMERICA
2      A02      KOREA
3      A03     GERMAN
4      A04     BRAZIL

In [46]:
selectExample.head()

  REGIONID    PRODUCT  YEARWEEK      QTY
0      A60   PRODUCT4    201402     71.0
1      A60  PRODUCT59    201402  22275.0
2      A60  PRODUCT34    201402   4463.0
3      A60  PRODUCT47    201402      0.0
4      A60  PRODUCT56    201402     23.0